# Generated by Django 5.0.2 on 2024-02-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='VideoURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
