# Generated by Django 5.0.2 on 2024-02-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='VideoURL',
            field=models.CharField(blank=True, default='https://youtu.be/1xD7IqFO9L8?si=LK5yYtCoKmKvqDjI', max_length=2048),
        ),
    ]
